# coding: utf-8

"""
    Upza Swagger

    Text processing server for upza  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: upza@upza.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException
from swagger_client.models.process_doc_request import ProcessDocRequest
from swagger_client.models.process_msg_request import ProcessMsgRequest
from swagger_client.models.rank_entities_request import RankEntitiesRequest


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_doc(self):
        """Test case for process_doc

        Process new doc  # noqa: E501
        """
        process_doc_request = ProcessDocRequest(url='https://en.wikipedia.org/wiki/Docker_(software)')
        self.api.process_doc(process_doc_request)
        process_doc_request = ProcessDocRequest(url='https://www.altoros.com/services/kubernetes-implementation?utm_medium=cpc&utm_source=google&utm_campaign=cfbl_service_kubernetes_implementation_usa_acquisition_search&hsa_cam=11173739894&hsa_grp=112155756643&hsa_mt=b&hsa_src=g&hsa_ad=477013342498&hsa_net=adwords&hsa_kw=kubernetes%20development&hsa_tgt=kwd-336266611630&hsa_ver=3&gclid=CjwKCAiAn7L-BRBbEiwAl9UtkGcTDgLWLmuJI9QvG-Lc2TD73JCorYoigUVTSiR7Dq1KlCMEcKSeMxoClGsQAvD_BwE')
        self.api.process_doc(process_doc_request)
        process_msg_request = ProcessMsgRequest(msg_id="my_message", msg_text="docker is awesome, ask me for any help!")
        self.api.process_msg(process_msg_request)
        rank_entities_request = RankEntitiesRequest(keywords=["docker", "kubernetes"], limit=1)
        ranked_entities = self.api.rank_entities(rank_entities_request)
        print(ranked_entities)
        found = 0
        for entity in ranked_entities.entities:
            if entity.entity_id in ["https://www.altoros.com/services/kubernetes-implementation?utm_medium=cpc&utm_source=google&utm_campaign=cfbl_service_kubernetes_implementation_usa_acquisition_search&hsa_cam=11173739894&hsa_grp=112155756643&hsa_mt=b&hsa_src=g&hsa_ad=477013342498&hsa_net=adwords&hsa_kw=kubernetes%20development&hsa_tgt=kwd-336266611630&hsa_ver=3&gclid=CjwKCAiAn7L-BRBbEiwAl9UtkGcTDgLWLmuJI9QvG-Lc2TD73JCorYoigUVTSiR7Dq1KlCMEcKSeMxoClGsQAvD_BwE"]:
                found += 1

        if found == 0:
            print("Failed")
            return -1

        print("Success")

    def test_process_msg(self):
        """Test case for process_msg

        Process new msg  # noqa: E501
        """
        pass

    def test_rank_entities(self):
        """Test case for rank_entities

        Rank Entities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
