# coding: utf-8

"""
    Upza Swagger

    Text processing server for upza  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: upza@upza.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rank_entities_response import RankEntitiesResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestRankEntitiesResponse(unittest.TestCase):
    """RankEntitiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRankEntitiesResponse(self):
        """Test RankEntitiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rank_entities_response.RankEntitiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
