# coding: utf-8

# flake8: noqa

"""
    Upza Swagger

    Text processing server for upza  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: upza@upza.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.entity import Entity
from swagger_client.models.process_doc_request import ProcessDocRequest
from swagger_client.models.process_msg_request import ProcessMsgRequest
from swagger_client.models.rank_entities_request import RankEntitiesRequest
from swagger_client.models.rank_entities_response import RankEntitiesResponse
