# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Entity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, entity_id: str=None, score: int=None):  # noqa: E501
        """Entity - a model defined in Swagger

        :param entity_id: The entity_id of this Entity.  # noqa: E501
        :type entity_id: str
        :param score: The score of this Entity.  # noqa: E501
        :type score: int
        """
        self.swagger_types = {
            'entity_id': str,
            'score': int
        }

        self.attribute_map = {
            'entity_id': 'entityId',
            'score': 'score'
        }

        self._entity_id = entity_id
        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> 'Entity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entity of this Entity.  # noqa: E501
        :rtype: Entity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def entity_id(self) -> str:
        """Gets the entity_id of this Entity.


        :return: The entity_id of this Entity.
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id: str):
        """Sets the entity_id of this Entity.


        :param entity_id: The entity_id of this Entity.
        :type entity_id: str
        """

        self._entity_id = entity_id

    @property
    def score(self) -> int:
        """Gets the score of this Entity.


        :return: The score of this Entity.
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score: int):
        """Sets the score of this Entity.


        :param score: The score of this Entity.
        :type score: int
        """

        self._score = score
