# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProcessMsgRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, msg_id: str=None, msg_text: str=None):  # noqa: E501
        """ProcessMsgRequest - a model defined in Swagger

        :param msg_id: The msg_id of this ProcessMsgRequest.  # noqa: E501
        :type msg_id: str
        :param msg_text: The msg_text of this ProcessMsgRequest.  # noqa: E501
        :type msg_text: str
        """
        self.swagger_types = {
            'msg_id': str,
            'msg_text': str
        }

        self.attribute_map = {
            'msg_id': 'msgId',
            'msg_text': 'msgText'
        }

        self._msg_id = msg_id
        self._msg_text = msg_text

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessMsgRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessMsgRequest of this ProcessMsgRequest.  # noqa: E501
        :rtype: ProcessMsgRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg_id(self) -> str:
        """Gets the msg_id of this ProcessMsgRequest.


        :return: The msg_id of this ProcessMsgRequest.
        :rtype: str
        """
        return self._msg_id

    @msg_id.setter
    def msg_id(self, msg_id: str):
        """Sets the msg_id of this ProcessMsgRequest.


        :param msg_id: The msg_id of this ProcessMsgRequest.
        :type msg_id: str
        """

        self._msg_id = msg_id

    @property
    def msg_text(self) -> str:
        """Gets the msg_text of this ProcessMsgRequest.


        :return: The msg_text of this ProcessMsgRequest.
        :rtype: str
        """
        return self._msg_text

    @msg_text.setter
    def msg_text(self, msg_text: str):
        """Sets the msg_text of this ProcessMsgRequest.


        :param msg_text: The msg_text of this ProcessMsgRequest.
        :type msg_text: str
        """

        self._msg_text = msg_text
