# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RankEntitiesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, entities: List[Entity]=None):  # noqa: E501
        """RankEntitiesResponse - a model defined in Swagger

        :param entities: The entities of this RankEntitiesResponse.  # noqa: E501
        :type entities: List[Entity]
        """
        self.swagger_types = {
            'entities': List[Entity]
        }

        self.attribute_map = {
            'entities': 'entities'
        }

        self._entities = entities

    @classmethod
    def from_dict(cls, dikt) -> 'RankEntitiesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RankEntitiesResponse of this RankEntitiesResponse.  # noqa: E501
        :rtype: RankEntitiesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def entities(self) -> List[Entity]:
        """Gets the entities of this RankEntitiesResponse.


        :return: The entities of this RankEntitiesResponse.
        :rtype: List[Entity]
        """
        return self._entities

    @entities.setter
    def entities(self, entities: List[Entity]):
        """Sets the entities of this RankEntitiesResponse.


        :param entities: The entities of this RankEntitiesResponse.
        :type entities: List[Entity]
        """

        self._entities = entities
