# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RankEntitiesRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, keywords: List[str]=None, limit: int=None):  # noqa: E501
        """RankEntitiesRequest - a model defined in Swagger

        :param keywords: The keywords of this RankEntitiesRequest.  # noqa: E501
        :type keywords: List[str]
        :param limit: The limit of this RankEntitiesRequest.  # noqa: E501
        :type limit: int
        """
        self.swagger_types = {
            'keywords': List[str],
            'limit': int
        }

        self.attribute_map = {
            'keywords': 'keywords',
            'limit': 'limit'
        }

        self._keywords = keywords
        self._limit = limit

    @classmethod
    def from_dict(cls, dikt) -> 'RankEntitiesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RankEntitiesRequest of this RankEntitiesRequest.  # noqa: E501
        :rtype: RankEntitiesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keywords(self) -> List[str]:
        """Gets the keywords of this RankEntitiesRequest.


        :return: The keywords of this RankEntitiesRequest.
        :rtype: List[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords: List[str]):
        """Sets the keywords of this RankEntitiesRequest.


        :param keywords: The keywords of this RankEntitiesRequest.
        :type keywords: List[str]
        """

        self._keywords = keywords

    @property
    def limit(self) -> int:
        """Gets the limit of this RankEntitiesRequest.


        :return: The limit of this RankEntitiesRequest.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this RankEntitiesRequest.


        :param limit: The limit of this RankEntitiesRequest.
        :type limit: int
        """

        self._limit = limit
