# coding: utf-8

"""
    Upza Swagger

    Text processing server for upza  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: upza@upza.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProcessMsgRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'msg_id': 'str',
        'msg_text': 'str'
    }

    attribute_map = {
        'msg_id': 'msgId',
        'msg_text': 'msgText'
    }

    def __init__(self, msg_id=None, msg_text=None):  # noqa: E501
        """ProcessMsgRequest - a model defined in Swagger"""  # noqa: E501

        self._msg_id = None
        self._msg_text = None
        self.discriminator = None

        if msg_id is not None:
            self.msg_id = msg_id
        if msg_text is not None:
            self.msg_text = msg_text

    @property
    def msg_id(self):
        """Gets the msg_id of this ProcessMsgRequest.  # noqa: E501


        :return: The msg_id of this ProcessMsgRequest.  # noqa: E501
        :rtype: str
        """
        return self._msg_id

    @msg_id.setter
    def msg_id(self, msg_id):
        """Sets the msg_id of this ProcessMsgRequest.


        :param msg_id: The msg_id of this ProcessMsgRequest.  # noqa: E501
        :type: str
        """

        self._msg_id = msg_id

    @property
    def msg_text(self):
        """Gets the msg_text of this ProcessMsgRequest.  # noqa: E501


        :return: The msg_text of this ProcessMsgRequest.  # noqa: E501
        :rtype: str
        """
        return self._msg_text

    @msg_text.setter
    def msg_text(self, msg_text):
        """Sets the msg_text of this ProcessMsgRequest.


        :param msg_text: The msg_text of this ProcessMsgRequest.  # noqa: E501
        :type: str
        """

        self._msg_text = msg_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessMsgRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessMsgRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
